services:
   networks:
      - rezo_td3_pma
      - rezo_td3_web
   volumes:
      vol_td3_web
   web:
      image: r480-php:8.2-apache
      build: .
      container_name: td3_web
      networks: 
         - rezo_td3_web
      ports: 
         - "8050:80"
      volumes: 
         - vol_td3_web: /var/www/html
   db:
      image: r408-mysql:5.7
      container_name: td3_db
      networks: 
         - rezo_td3_pma
         - rezo_td3_web
      environment: 
         - MYSQL_USER=${DBUSER}
         - MYSQL_PASSWORD=${DBPWD}
         - MYSQL_ROOT_PASSWORD=${ROOTP}
         - MYSQL_DATABASE=${DB}
   pma:
      image: r408-phpmyadmin:5.2
      container_name: td3_pma
      networks: 
         - rezo_td3_pma
      ports: 
         - "8060:80"
      environment:
         - PMA_HOST=${PMA_HOST}
   