TYPE DNOMF POSSREP {DNOMF CHAR};
TYPE DVILLE POSSREP {DVILLE CHAR};

TYPE DNOFOUR POSSREP {
	SNUM CHAR
	CONSTRAINT LENGTH(SNUM) <= 3
	AND STARTS_WITH(SNUM, 'F')
	AND IS_DIGITS(SUBSTRING(SNUM,1))
};

VAR FOURNISSEUR REAL RELATION {
	NOFOUR DNOFOUR, 
	NOMF DNOMF, 
	VILLE DVILLE} KEY {NOFOUR};

type DNOMP possrep {DNOMF CHAR};
type DCOULEUR possrep {DCOUL CHAR};
type DNOPRODUIT possrep {
	DNOPROD CHAR
	CONSTRAINT LENGTH(DNOPROD) <= 3
	AND STARTS_WITH(DNOPROD, 'P')
	AND IS_DIGITS(SUBSTRING(DNOPROD,1))
};

VAR PRODUIT REAL RELATION {
	NOPRODUIT DNOPRODUIT,
	COULEUR DCOULEUR,
	NOMP DNOMP,
	ORIGINE DVILLE
} KEY{NOPRODUIT};


type DQUANTITE possrep{
	DQTE INTEGER
	CONSTRAINT DQTE <= 10 AND DQTE >=1 
};

var FOURNITURE real relation{
	NOFOUR		DNOFOUR,
	NOPRODUIT	DNOPRODUIT,
	QUANTITE	DQUANTITE
} key {NOFOUR,NOPRODUIT};

CONSTRAINT fourniture_fk_four
	FOURNITURE{NOFOUR} <= FOURNISSEUR{NOFOUR};
CONSTRAINT fourniture_fk_prod
	FOURNITURE{NOPRODUIT} <= PRODUIT{NOPRODUIT};


FOURNISSEUR := RELATION {
	TUPLE {NOFOUR DNOFOUR("F1"), NOMF DNOMF("Bourhis"),  VILLE DVILLE("Paris")},
	TUPLE {NOFOUR DNOFOUR("F2"), NOMF DNOMF("Bourhis"), VILLE DVILLE("Paris")},	
	TUPLE {NOFOUR DNOFOUR("F3"), NOMF DNOMF("Collet"),  VILLE DVILLE("Reims")},
	TUPLE {NOFOUR DNOFOUR("F4"), NOMF DNOMF("Bossuet"),  VILLE DVILLE("Dijon")},
	TUPLE {NOFOUR DNOFOUR("F5"), NOMF DNOMF("Mercier"),  VILLE DVILLE("Riec")},
	TUPLE {NOFOUR DNOFOUR("F6"), NOMF DNOMF("Tanguy"),  VILLE DVILLE("Lannion")}
};

PRODUIT := RELATION {
	TUPLE {NOPRODUIT DNOPRODUIT("P1"), NOMP DNOMP("Cassis"), COULEUR DCOULEUR("Rouge"), ORIGINE DVILLE("Dijon")},
	TUPLE {NOPRODUIT DNOPRODUIT("P2"), NOMP DNOMP("Champagne"), COULEUR DCOULEUR("Blanc"), ORIGINE DVILLE("Reims")},
	TUPLE {NOPRODUIT DNOPRODUIT("P3"), NOMP DNOMP("Huitre"), COULEUR DCOULEUR("Vert"), ORIGINE DVILLE("Riec")},
	TUPLE {NOPRODUIT DNOPRODUIT("P4"), NOMP DNOMP("Moutarde"), COULEUR DCOULEUR("Jaune"), ORIGINE DVILLE("Dijon")},
	TUPLE {NOPRODUIT DNOPRODUIT("P5"), NOMP DNOMP("Salade"), COULEUR DCOULEUR("Vert"), ORIGINE DVILLE("Nice")},
	TUPLE {NOPRODUIT DNOPRODUIT("P6"), NOMP DNOMP("Cornichon"), COULEUR DCOULEUR("Vert"), ORIGINE DVILLE("Dijon")},
	TUPLE {NOPRODUIT DNOPRODUIT("P7"), NOMP DNOMP("Muscadet"), COULEUR DCOULEUR("Blanc"), ORIGINE DVILLE("Nantes")}
};

FOURNITURE := RELATION {
	TUPLE {NOFOUR DNOFOUR("F1"), NOPRODUIT DNOPRODUIT("P1"), QUANTITE DQUANTITE(1)},
	TUPLE {NOFOUR DNOFOUR("F1"), NOPRODUIT DNOPRODUIT("P4"), QUANTITE DQUANTITE(1)},
	TUPLE {NOFOUR DNOFOUR("F1"), NOPRODUIT DNOPRODUIT("P5"), QUANTITE DQUANTITE(8)},
	TUPLE {NOFOUR DNOFOUR("F1"), NOPRODUIT DNOPRODUIT("P6"), QUANTITE DQUANTITE(2)},
	TUPLE {NOFOUR DNOFOUR("F2"), NOPRODUIT DNOPRODUIT("P2"), QUANTITE DQUANTITE(1)},
	TUPLE {NOFOUR DNOFOUR("F2"), NOPRODUIT DNOPRODUIT("P4"), QUANTITE DQUANTITE(1)},
	TUPLE {NOFOUR DNOFOUR("F3"), NOPRODUIT DNOPRODUIT("P2"), QUANTITE DQUANTITE(5)},
	TUPLE {NOFOUR DNOFOUR("F3"), NOPRODUIT DNOPRODUIT("P4"), QUANTITE DQUANTITE(1)},
	TUPLE {NOFOUR DNOFOUR("F4"), NOPRODUIT DNOPRODUIT("P4"), QUANTITE DQUANTITE(2)},
	TUPLE {NOFOUR DNOFOUR("F4"), NOPRODUIT DNOPRODUIT("P5"), QUANTITE DQUANTITE(7)},
	TUPLE {NOFOUR DNOFOUR("F4"), NOPRODUIT DNOPRODUIT("P6"), QUANTITE DQUANTITE(3)},
	TUPLE {NOFOUR DNOFOUR("F5"), NOPRODUIT DNOPRODUIT("P3"), QUANTITE DQUANTITE(10)}
};


/*Exercice 3 :

1) PRODUIT{NOMP}

2) PRODUIT WHERE ORIGINE = DVILLE("Dijon")

3) (PRODUIT WHERE ORIGINE = DVILLE("Dijon")){NOMP}

4) FOURNISSEUR{NOFOUR}

5) FOURNISSEUR{NOFOUR} MINUS FOURNITURE{NOFOUR} 

6) (FOURNITURE WHERE NOPRODUIT = DNOPRODUIT("P6")){NOFOUR}

7) (FOURNITURE WHERE NOPRODUIT <> DNOPRODUIT('P6')){NOFOUR}

8) (FOURNISSEUR MINUS (FOURNITURE WHERE NOPRODUIT = DNOPRODUIT("P6"))){NOFOUR}

9) (FOURNITURE MINUS (FOURNITURE WHERE NOPRODUIT = DNOPRODUIT("P6"))){NOFOUR}

10) FOURNITURE{NOFOUR} MINUS (FOURNITURE  WHERE NOPRODUIT <> DNOPRODUIT('P6'))

11) (FOURNITURE WHERE NOPRODUIT = DNOPRODUIT('P4') OR NOPRODUIT = DNOPRODUIT('P6')){NOFOUR}

12) (FOURNITURE WHERE NOPRODUIT = DNOPRODUIT("P6")){NOFOUR} INTERSECT (FOURNITURE WHERE NOPRODUIT = DNOPRODUIT("P4")){NOFOUR}

13) FOURNITURE{NOFOUR} MINUS(
	FOURNITURE WHERE NOPRODUIT = DNOPRODUIT('P4') 
	OR NOPRODUIT = DNOPRODUIT('P6')
){NOFOUR}

14) (FOURNITURE JOIN FOURNISSEUR WHERE NOPRODUIT = DNOPRODUIT("P6")){NOFOUR, NOMF}

15) (FOURNITURE){NOFOUR} MINUS(
	FOURNITURE WHERE NOPRODUIT = DNOPRODUIT('P4') 
	OR NOPRODUIT = DNOPRODUIT('P6')
){NOFOUR}
JOIN 
FOURNISSEUR{ALL BUT VILLE}

16) (FOURNISSEUR JOIN FOURNITURE JOIN PRODUIT WHERE VILLE = ORIGINE){NOMFOUR, NOMF, VILLE}

17) (
		(
			PRODUIT{NOPRODUIT, COULEUR} RENAME {NOPRODUIT AS NOP1}
			JOIN 
			PRODUIT{NOPRODUIT, COULEUR} RENAME {NOPRODUIT AS NOP2}
		)WHERE NOP1 < NOP2
	){NOP1, NOP2}

18) 